server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://202.206.221.94/wechatapp?useSSL=false&serverTimezone=UTC
    data-username: root
    password: Pan102887@qq.com
    initialize: true
  jpa:
    database: mysql
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update







